### ISSUE TITLE
get_ds uses a "yes_leap" calendar

### ISSUE THREAD

**Issue by djk2120** [djk2120/CLM5PPE#5]
should be noleap to comport with CESM

**Comment by katiedagon** [comment]
Proposed change to `get_ds` function for fixing monthly time indices:
`ds['time']=xr.cftime_range(yr0_full,periods=len(ds.time),freq='MS',calendar='noleap')`

Alternatively, can use `time_bnds` attribute to adjust the data as in this [ESDS FAQ](https://ncar.github.io/esds/faq/#dealing-with-cesm-monthly-output-is-there-something-wrong-with-time).

**Comment by djk2120** [comment]
Resolved via 737bca3e0d81f6b004319ac18a8b449faf1d00a4
